# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6bd7217756ae4ece121f2adcb2a0e0e9e121c18ffc50b0476524019d0000f746b3e4e1ea2b132c99d6fc20bc9d13dc07cc0ee3c946c0be767493acb4c5155b60

test:
  secret_key_base: 36dbb356e0da0a6a91984027b9481cdee951304865905c6332547cc998e37e2065b6d7855808b66ca972294271c2cbd2992fb3a79681bfbb9db455248713d72d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
